import { connect } from '../index'
import { parse, stringify } from './pure'
const blns = require('blns')
require('dotenv').config()

const sample_data = {
    people: [{ name: 'john', settings: { mode: 1, likes_spam_email: false } }, { name: 'sandy', mood: 'unknown' }],
    animals: [{ name: 'cow', age: 2 }, { name: 'sheep', age: 8.2, favorite_color: null }, { name: 'donkey', age: 1 }]
}

const redibase = connect(process.env.redis)

beforeEach(async () => {
    await redibase.delete('')
})

afterAll(async () => {
    await redibase.quit()
})

// test.only('Can use lua', async () => {
//     const val = JSON.parse(`{"elPFHv1j-J":{"id":"elPFHv1j-J",
//     "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":55},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "zjxdQuG1e4":{"id":"zjxdQuG1e4",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":53},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "k_v-TDv7mq":{"id":"k_v-TDv7mq",
// "type":"product",
// "vendor_id":4,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "failed_attempts":0,
// "started_at":"2020-03-25T04:42:57.397Z",
// "status":"running",
// "params":{"product_id":60},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "sre0zchouYm":{"id":"sre0zchouYm",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "failed_attempts":0,
// "started_at":"2020-03-25T04:42:57.405Z",
// "status":"running",
// "params":{"product_id":93},
// "subtasks_completed":{"inventory":false,

// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "2M-ystOM24q":{"id":"2M-ystOM24q",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "failed_attempts":0,
// "started_at":"2020-03-25T04:42:57.406Z",
// "status":"running",
// "params":{"product_id":130},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "qY6n5XU2YI":{"id":"qY6n5XU2YI",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "failed_attempts":0,
// "started_at":"2020-03-25T04:42:57.408Z",
// "status":"running",
// "params":{"product_id":58},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "JAcb1O8vF-Q":{"id":"JAcb1O8vF-Q",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "failed_attempts":0,
// "started_at":"2020-03-25T04:42:57.409Z",
// "status":"running",
// "params":{"product_id":77},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "UvxQi408dFM":{"id":"UvxQi408dFM",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":114},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "nOZJl0Tr_tR":{"id":"nOZJl0Tr_tR",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":133},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "W6W1tZL6gsE":{"id":"W6W1tZL6gsE",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":123},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "1TtWDKR4o4":{"id":"1TtWDKR4o4",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":77},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "DShbpJ4i_":{"id":"DShbpJ4i_",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "failed_attempts":0,
// "started_at":"2020-03-25T04:28:17.322Z",
// "status":"running",
// "params":{"product_id":47},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "UYdTL3PGxy4":{"id":"UYdTL3PGxy4",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":138},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "uAI_sODL6bW":{"id":"uAI_sODL6bW",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":125},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "DA38zL06pe":{"id":"DA38zL06pe",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":62},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Lo-uhGRkiC":{"id":"Lo-uhGRkiC",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":57},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "vDa5HzJFeBU":{"id":"vDa5HzJFeBU",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":123},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "r8WsRJiyt_":{"id":"r8WsRJiyt_",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":63},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "BTfYKZrMCj2":{"id":"BTfYKZrMCj2",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":109},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "DrfWuad4jkT":{"id":"DrfWuad4jkT",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":92},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "8yORWd0936v":{"id":"8yORWd0936v",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":93},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "SC5eCyeAik7":{"id":"SC5eCyeAik7",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":136},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "fEFWFmD9DZ":{"id":"fEFWFmD9DZ",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":66},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "x6GDYOhD7w-":{"id":"x6GDYOhD7w-",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":104},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Ls1mm2ePJx2":{"id":"Ls1mm2ePJx2",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":128},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "qyB2UoeZlS7":{"id":"qyB2UoeZlS7",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":147},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "PKyzpKwMy":{"id":"PKyzpKwMy",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":53},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "eDSMzGmTa4":{"id":"eDSMzGmTa4",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":2,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":57},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},

// "Bnqzqbcq2S":{"id":"Bnqzqbcq2S",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":62},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "QOhLusOPYM4":{"id":"QOhLusOPYM4",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":114},

// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "qtZbOPcDaLg":{"id":"qtZbOPcDaLg",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":87},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "7UQXBK_NPm":{"id":"7UQXBK_NPm",
// "type":"product",
// "vendor_id":4,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":48},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "cFTkVt1hZtq":{"id":"cFTkVt1hZtq",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":141},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "PF8bU57w99d":{"id":"PF8bU57w99d",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":99},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "HeNaMnY0ISY":{"id":"HeNaMnY0ISY",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":101},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "_p3bhAmGudv":{"id":"_p3bhAmGudv",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":125},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "BK5XrNG-Sex":{"id":"BK5XrNG-Sex",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":113},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "4xPRAOpCk5R":{"id":"4xPRAOpCk5R",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":115},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "IlWIHL3dnYa":{"id":"IlWIHL3dnYa",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":94},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "vAX1U5MOrTI":{"id":"vAX1U5MOrTI",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":126},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "4Gq_wrBZm5U":{"id":"4Gq_wrBZm5U",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":2,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":72},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "v4FpyIbFcGi":{"id":"v4FpyIbFcGi",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":106},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Oz-Bl_g1gJ9":{"id":"Oz-Bl_g1gJ9",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":143},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "18zZYs-nrBO":{"id":"18zZYs-nrBO",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":100},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "jCYgLEuIVQO":{"id":"jCYgLEuIVQO",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":92},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Xm7v3RIaFJ":{"id":"Xm7v3RIaFJ",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":59},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "CoGEOVHyP0i":{"id":"CoGEOVHyP0i",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":68},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "SUa6zaLvSGn":{"id":"SUa6zaLvSGn",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":87},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "d831lsJFbC":{"id":"d831lsJFbC",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":68},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "ifqEkwJR6nZ":{"id":"ifqEkwJR6nZ",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":126},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "kckt4vVzFiE":{"id":"kckt4vVzFiE",
// "type":"product",
// "vendor_id":16,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":95},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "o0pAyvm-92m":{"id":"o0pAyvm-92m",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":110},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Lzc2QNtLSZ":{"id":"Lzc2QNtLSZ",
// "type":"product",
// "vendor_id":4,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":50},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "WvajeGNUaWi":{"id":"WvajeGNUaWi",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,

// "params":{"product_id":107},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "8jAsifBVqG":{"id":"8jAsifBVqG",
// "type":"product",
// "vendor_id":4,
// "store_id":1,
// "priority":2,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":51},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Pj9HvtX2_0s":{"id":"Pj9HvtX2_0s",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":148},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "jSe_DsuauC3":{"id":"jSe_DsuauC3",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":146},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "NUdEqWg6lo":{"id":"NUdEqWg6lo",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":56},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "4lHv1jrU5RG":{"id":"4lHv1jrU5RG",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":85},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "WctDS-EYae7":{"id":"WctDS-EYae7",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":101},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "1tnAG4Cr1TO":{"id":"1tnAG4Cr1TO",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":127},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "lNRiltBoLtU":{"id":"lNRiltBoLtU",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":82},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "FKv6m4rc2C":{"id":"FKv6m4rc2C",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":58},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "xeF72ajlPs6":{"id":"xeF72ajlPs6",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":139},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "ihn2GW7J52n":{"id":"ihn2GW7J52n",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":137},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "WmBymJiQP49":{"id":"WmBymJiQP49",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":143},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "k_1SZjqbfSl":{"id":"k_1SZjqbfSl",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":142},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "5DZmvmuoab":{"id":"5DZmvmuoab",
// "type":"product",
// "vendor_id":4,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":54},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "RbIghp0fXGj":{"id":"RbIghp0fXGj",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":129},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "jf5ZgyXtc6C":{"id":"jf5ZgyXtc6C",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":94},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "_wdKDcLe96-":{"id":"_wdKDcLe96-",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":111},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "DfNjB10nzW":{"id":"DfNjB10nzW",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":66},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "539B57_lVKs":{"id":"539B57_lVKs",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":149},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "ab_ar2_y_YB":{"id":"ab_ar2_y_YB",
// "type":"product",
// "vendor_id":4,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":52},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "qWdoIp9D-k8":{"id":"qWdoIp9D-k8",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":144},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "3o7oTTOgWhp":{"id":"3o7oTTOgWhp",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":138},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "_43CVrsRCD":{"id":"_43CVrsRCD",
// "type":"product",
// "vendor_id":4,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":60},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "i8438HQFpML":{"id":"i8438HQFpML",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":2,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":108},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "ZaWlNKTqAeU":{"id":"ZaWlNKTqAeU",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":139},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "7HmtlNvTR0N":{"id":"7HmtlNvTR0N",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":130},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "XLMCp0zJeTj":{"id":"XLMCp0zJeTj",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":111},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "GNhTmOpQm_x":{"id":"GNhTmOpQm_x",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":86},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "7LnpltgXkwO":{"id":"7LnpltgXkwO",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":131},
// "subtasks_completed":{"inventory":false,
// "price":false,

// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "AZaM4UkXJEV":{"id":"AZaM4UkXJEV",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":102},

// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "Y14aN5k1mlt":{"id":"Y14aN5k1mlt",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":145},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "I-hpplnLJbY":{"id":"I-hpplnLJbY",
// "type":"product",
// "vendor_id":6,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":107},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "xLOrWotRZcf":{"id":"xLOrWotRZcf",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":134},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "ki_jOieweoM":{"id":"ki_jOieweoM",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":100},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "B6UKtVC8n5s":{"id":"B6UKtVC8n5s",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":128},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "1j-X4eXLZ3":{"id":"1j-X4eXLZ3",
// "type":"product",
// "vendor_id":4,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":52},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "AM6l-tRSNi7":{"id":"AM6l-tRSNi7",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":124},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "OVgrYxiAkv":{"id":"OVgrYxiAkv",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":75},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "feYDM_eNuvc":{"id":"feYDM_eNuvc",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":148},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "PQB1N4ObPFv":{"id":"PQB1N4ObPFv",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":129},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "GQxgGnFdzP":{"id":"GQxgGnFdzP",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":59},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "jeYE-eCnON8":{"id":"jeYE-eCnON8",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":96},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "yRCBiswqHGl":{"id":"yRCBiswqHGl",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":112},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "2U6smxhxrlM":{"id":"2U6smxhxrlM",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":137},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "_mg34Agnx6D":{"id":"_mg34Agnx6D",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":106},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "j9URMUZNzLF":{"id":"j9URMUZNzLF",
// "type":"product",
// "vendor_id":4,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":103},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "eYdOqfLE64L":{"id":"eYdOqfLE64L",
// "type":"product",
// "vendor_id":6,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":115},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "dYQLiQQe6n":{"id":"dYQLiQQe6n",
// "type":"product",
// "vendor_id":3,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":63},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "VwR0lKc6nGS":{"id":"VwR0lKc6nGS",
// "type":"product",
// "vendor_id":3,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":135},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "rOtRXXHIXh":{"id":"rOtRXXHIXh",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":74},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "PNf4BEk4OGF":{"id":"PNf4BEk4OGF",
// "type":"product",
// "vendor_id":16,
// "store_id":2,
// "priority":3,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":95},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "srTkjnQrY70":{"id":"srTkjnQrY70",
// "type":"product",
// "vendor_id":1,
// "store_id":1,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":82},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false,
// "product":false}},
// "TYyb0gO8wav":{"id":"TYyb0gO8wav",
// "type":"product",
// "vendor_id":1,
// "store_id":2,
// "priority":1,
// "queued_at":"2020-03-25T04:27:57.211Z",
// "status":"pending",
// "failed_attempts":0,
// "params":{"product_id":98},
// "subtasks_completed":{"inventory":false,
// "price":false,
// "images":false,
// "variants":false,
// "metas":false
// ,
// "product":false}}}`)
//     const val_small = {
//         "elPFHv1j-J": {
//             "id": "elPFHv1j-J",
//             "type": "product",
//             "vendor_id": 3,
//             "store_id": 1,
//             "priority": 3,
//             "queued_at": "2020-03-25T04:27:57.211Z",
//             "status": "pending",
//             "failed_attempts": 0,
//             "params": {
//                 "product_id": 55
//             },
//             "subtasks_completed": {
//                 "inventory": false,
//                 "price": false,
//                 "images": false,
//                 "variants": false,
//                 "metas": false,
//                 "product": false
//             }
//         },
//         "zjxdQuG1e4": {
//             "id": "zjxdQuG1e4",
//             "type": "product",
//             "vendor_id": 1,
//             "store_id": 1,
//             "priority": 3,
//             "queued_at": "2020-03-25T04:27:57.211Z",
//             "status": "pending",
//             "failed_attempts": 0,
//             "params": {
//                 "product_id": 53
//             },
//             "subtasks_completed": {
//                 "inventory": false,
//                 "price": false,
//                 "images": false,
//                 "variants": false,
//                 "metas": false,
//                 "product": false
//             }
//         },
//         "k_v-TDv7mq": {
//             "id": "k_v-TDv7mq",
//             "type": "product",
//             "vendor_id": 4,
//             "store_id": 1,
//             "priority": 1,
//             "queued_at": "2020-03-25T04:27:57.211Z",
//             "failed_attempts": 0,
//             "started_at": "2020-03-25T04:42:57.397Z",
//             "status": "running",
//             "params": {
//                 "product_id": 60
//             },
//             "subtasks_completed": {
//                 "inventory": false,
//                 "price": false,
//                 "images": false,
//                 "variants": false,
//                 "metas": false,
//                 "product": false
//             }
//         },
//         "sre0zchouYm": {
//             "id": "sre0zchouYm",
//             "type": "product",
//             "vendor_id": 1,
//             "store_id": 1,
//             "priority": 1,
//             "queued_at": "2020-03-25T04:27:57.211Z",
//             "failed_attempts": 0,
//             "started_at": "2020-03-25T04:42:57.405Z",
//             "status": "running",
//             "params": {
//                 "product_id": 93
//             },
//             "subtasks_completed": {
//                 "inventory": false,
//                 "price": false,
//                 "images": false,
//                 "variants": false,
//                 "metas": false,
//                 "product": false
//             }
//         }
//     }
//     const val_tiny = {
//         "sre0zchouYm": {
//             "id": "sre0zchouYm",
//             "type": "product",
//             "vendor_id": 1,
//             "store_id": 1,
//             "priority": 1,
//             "queued_at": "2020-03-25T04:27:57.211Z",
//             "failed_attempts": 0,
//             "started_at": "2020-03-25T04:42:57.405Z",
//             "status": "running",
//             "params": {
//                 "product_id": 93
//             },
//             "subtasks_completed": {
//                 "inventory": false,
//                 "price": false,
//                 "images": false,
//                 "variants": false,
//                 "metas": false,
//                 "product": false
//             }
//         }
//     }
//     await redibase.set('', { job_list: val })
//     const x = await redibase.get('')
//     return x
// })

test('Indices are properly merged', async () => {
    const sample_addition = { name: 'chicken', age: 3.14 }

    const r1 = await redibase.set('', sample_data)
    const r2 = await redibase.set('animals.3', sample_addition)
    const r3 = await redibase.get('')
    expect(r3.animals[3]).toEqual(sample_addition)
})


test('can set at locations that do not exist', async () => {
    await redibase.set('my.name.is', 'jeff')
    const result = await redibase.get('my')
    expect(result).toEqual({ name: { is: 'jeff' } })
})

test('Can store and retrieve json', async () => {
    const r1 = await redibase.set('', sample_data)
    const r2 = await redibase.get('people.0.name')
    expect(r2).toEqual('john')
    const r25 = await redibase.get('')
    expect(r25).toEqual(sample_data)

    const r3 = await redibase.set('animals.1.favorite_color', 'white')
    const r4 = await redibase.get('animals.1.favorite_color')
    expect(r4).toEqual('white')

    const change = { name: 'john' }
    const r5 = await redibase.set('people.0', change)
    const r6 = await redibase.get('people.0')
    expect(r6).toEqual(change)

    const r7 = await redibase.delete('animals.0')
    const r8 = await redibase.get('animals.0')
    expect(r8).toEqual(null)
})

test('Can store naughty strings and different types as values', async () => {
    const store_and_retrieve = async (path, value) => {
        const r1 = await redibase.set(path, value)
        const r2 = await redibase.get(path)
        expect(r2).toEqual(value)
    }
    const values_to_try = [

        true, false,
        null, undefined,
        1, -1, 0, 1.11, Infinity, -Infinity,
        'throw new Error("oops")',
        '/', '.', '-', '=', '_',
        'object', 'function', 'string', ...blns.slice(0, 5)

    ]

    for (let i = 0; i < values_to_try.length; i++) {
        await store_and_retrieve('key1', values_to_try[i])
    }


})

test('if no key return null', async () => {
    const delete_response = await redibase.delete('shmey1')
    const get_response = await redibase.get('shmey1')
    expect(get_response).toEqual(null)

})
test('can set on the root layer', async () => {
    const r1 = await redibase.set('', sample_data)
    const r2 = await redibase.set('animals', { likes_chicken: true })
    const r3 = await redibase.get('')
    expect(r3).toEqual({ ...sample_data, animals: { likes_chicken: true } })
})

test('can stringify and parse', () => {
    expect(parse(stringify(1))).toEqual(1)
    expect(parse(stringify(['test.0']))).toEqual(['test.0'])
    expect(parse(stringify([1, 2, 'test.0']))).toEqual([1, 2, 'test.0'])
    expect(parse(stringify(Infinity))).toEqual(Infinity)
    expect(parse(stringify(false))).toEqual(false)
    expect(parse(stringify(true))).toEqual(true)
    expect(parse(stringify(null))).toEqual(null)
    expect(parse(stringify('null'))).toEqual('null')
    expect(parse(stringify(undefined))).toEqual(undefined)
})

test('Should handle objects with funny key names', async () => {
    const r1 = await redibase.set('key1', { 'not.ok': 'mate' }).catch((err) => { return err })
    const r2 = await redibase.set('key1', { 2: 'mate' }).catch((err) => { return err })
    const r3 = await redibase.set('key1', { 'p_p': undefined })
    expect(r1.message).toEqual('"not.ok" is not allowed')
    expect(r2.message).toEqual('"2" is not allowed')
    expect(r3).toEqual(undefined)
})

test('Should pubsub to changes', (done) => {
    (async () => {
        await redibase.on('weather', async (new_val, old_val) => {
            const new_weather = new_val - 1
            console.log('setting weather to', new_weather)
            if (new_val === 0) {
                console.log('welcome to canada')
                done()
            } else if (new_val > 0) {
                redibase.set('weather', new_weather)
            }
        })
        const initial_weather = 35
        await redibase.set('weather', initial_weather)
    })()
})

test.skip('delete deletes key indices right away', (done) => {
    (async () => {
        await redibase.set('', { people: { are: { here: true } } })
        redibase.on('', async () => {
            const r1 = await redibase.get('people')
            expect(Object.keys(r1).length).toEqual(0)
            done()
        })
        await redibase.delete('people.are')
    })()
})

test.skip('delete deletes key indices right away', (done) => {
    (async () => {
        await redibase.set('', { people: ['john', 'mary', 'edward'] })
        await redibase.on('', async () => {
            const r1 = await redibase.get('')
            expect(Object.keys(r1).length).toEqual(0)
            done()
        })
        await redibase.delete('')
    })()
})
test.todo('values can become indexes eg my.name = "shmerel" then set my.name.last = "baker" and expect name to turn into an object')
test.todo('can unsubscribe')
test.todo('when subprop changes whole object is sent to on fn')
test.skip('subscribing gives nested data', done => {
    (async () => {
        const test_data = { animals: [{ name: 'cow', age: 16 }] }
        await redibase.set('', test_data)
        redibase.on('animals', (new_value, old_value) => {
            expect(old_value).toEqual(test_data)
            expect(new_value.animals[0]).toEqual({ name: 'sheep', age: 16 })
        })
        await redibase.set('animals.0.name', 'sheep')
    })()
})
test.todo('can store NaN, -0, [], {}')